2023-07-14 10:07:00,588 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 10:07:08,758 ERROR: Exception on /index [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 23, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/base.html", line 18, in template
    <a href="{{ url_for('explore) }}">Explore</a>
jinja2.exceptions.TemplateSyntaxError: unexpected char "'" at 508
2023-07-14 10:07:34,119 ERROR: Exception on /user/giacomo [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 65, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/user.html", line 27, in block 'content'
    {% include '_post.html' %}
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/_post.html", line 5, in template
    <a href="{{ url)for('user', username=post.author.username) }}">
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
2023-07-14 10:08:02,814 ERROR: Exception on /user/giacomo [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 65, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/user.html", line 27, in block 'content'
    {% include '_post.html' %}
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/templates/_post.html", line 5, in template
    <a href="{{ url)for('user', username=post.author.username) }}">
jinja2.exceptions.TemplateSyntaxError: unexpected ')'
2023-07-14 10:09:40,985 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 10:21:18,977 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
