2023-07-14 17:21:32,266 ERROR: Exception on /index [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 23, in index
    posts = current_user.followed_posts().paginate( page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:25:40,198 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 17:25:43,344 ERROR: Exception on /index [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 23, in index
    posts = current_user.followed_posts().paginate( page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:25:45,523 ERROR: Exception on /index [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 23, in index
    posts = current_user.followed_posts().paginate( page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:25:51,436 ERROR: Exception on /index [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 23, in index
    posts = current_user.followed_posts().paginate( page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:25:53,490 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(page, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:28:06,497 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
2023-07-14 17:28:09,315 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:28:36,619 ERROR: Exception on /explore [GET] [in /home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/albertocampagnolo/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/routes.py", line 124, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(pages, app.config['POSTS_PER_PAGE'], False)
TypeError: Query.paginate() takes 1 positional argument but 4 were given
2023-07-14 17:29:44,557 INFO: Microblog startup [in /home/albertocampagnolo/Desktop/Flask_mega_tutorial_book/microblog/app/__init__.py:48]
